language: python
python: 
  - '3.10'

services:
  - docker

before_skript: pip install docker-compose

script: 
  - docker-compose run app sh -c "python manage.py test && flake8"
  
# sudo gitlab-rake gitlab:env:info

# django-tests:
#   stage: test
#   script:
#     - pip install docker-compose
#     - docker-compose run app sh -c "python manage.py test && flake8"
